GET http://localhost:3000/customer/2
Content-Type: application/json
Authorization: bearer token


### création d'un compte seller
POST http://localhost:3000/seller/signup
Content-Type: application/json

{
    "gender": "F",
    "email": "abdoula@gmail.com",
    "password": "abdoula",
    "passwordConfirm" : "abdoula",
    "lastname": "Exploratrice",
    "firstname": "Dora",
    "phone_number": "0661737865",
    "street_name": "boulevard Tokyo",
    "street_number": "13",
    "city": "Paris",
    "zipcode": 75000,
    "picture_url": "https://img-4.linternaute.com/lUM_6jl2EZ6NpWNkH70wj25s0aw=/1240x/1b2dbaad11b84ee8bde02cfcd0b823dd/ccmcms-linternaute/83141.jpg",
    "siret": 82365600199999,
    "shop_name": "Chez David",
    "shop_presentation": "Je suis vendeur de légumes reconverti dans les roses"
}

### création d'un compte customer
POST http://localhost:3000/customer/signup
Content-Type: application/json

{
    "gender": "F",
    "email": "abdouladu06@gmail.com",
    "password": "abdoula",
    "passwordConfirm" : "abdoula",
    "lastname": "Exploratrice",
    "firstname": "Dora",
    "phone_number": "0661737865",
    "street_name": "boulevard Tokyo",
    "street_number": "13",
    "city": "Paris",
    "zipcode": 75000
}


### connexion à un compte seller
POST http://localhost:3000/seller/login
Content-Type: application/json

{
    "email": "abdoula@gmail.com",
    "password": "abdoula"
}


### connexion à un compte customer
POST http://localhost:3000/customer/login
Content-Type: application/json

{
    "email": "abdouladu06@gmail.com",
    "password": "abdoula"
}

### Editer un compte seller
PATCH http://localhost:3000/customer/5
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTYxNTEyMDM0NCwiZXhwIjoxNjE1MTMxMTQ0fQ.hMr5zLJXgI9e6imnN4b_0b-0Djg4C1mQJMLDUH3iSd0

{
    "gender": "M",
    //"email": "abdoula06@gmail.com",
    "password": "soismonami",
    "passwordConfirm" : "soismonami",
    "lastname": "Exploratrice",
    "firstname": "Dora",
    "phone_number": "0661737865",
    "street_name": "boulevard Tokyo",
    "street_number": "13",
    "city": "Paris",
    "zipcode": 75000,
    "picture_url": "https://img-4.linternaute.com/lUM_6jl2EZ6NpWNkH70wj25s0aw=/1240x/1b2dbaad11b84ee8bde02cfcd0b823dd/ccmcms-linternaute/83141.jpg",
    "siret": 82365600199999,
    "shop_name": "Chez David",
    "shop_presentation": "Je suis vendeur de légumes reconverti dans les roses"
}

### Editer un compte seller
PATCH http://localhost:3000/seller/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE2MTUxMjMyMTAsImV4cCI6MTYxNTEzNDAxMH0.j3nrZMLOR-hlD2GDY0IdqU9gLDPdOYmHowJCrKhoNcM

{
    "gender": "F",
    
    "password": "soismonami",
    "passwordConfirm" : "soismonami",
    "lastname": "Exploratrice",
    "firstname": "Dora la vieille du 06",
    "phone_number": "0661737865",
    "street_name": "boulevard Sangoku",
    "street_number": "13",
    "city": "Paris",
    "zipcode": 75000,
    "picture_url": "https://img-4.linternaute.com/lUM_6jl2EZ6NpWNkH70wj25s0aw=/1240x/1b2dbaad11b84ee8bde02cfcd0b823dd/ccmcms-linternaute/83141.jpg",
    "siret": 82365600199999,
    "shop_name": "Chez David",
    "shop_presentation": "Tu es reconverti dans les roses",
    "shop_me_if_you_can" : "Ok bro"
}